# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 542b05483b6791b7b568db928712dfb59fa26c00e113e9c3ed2e5a77e123c097a9f33ae777353bfd5e60b62abf5e28806de68f31020082b5c50c04a89fd8ada4

test:
  secret_key_base: 88efe511cf9ba467c8017f532c0a6988264bc5e0918c6459d27a79a76d8d35900030e0b7705c93d1e75d1c44163c13b5e083fa3fb0701204ed1f3b91570dde27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
